const notificationMessages = {
    "account_not_active" : "Le compte n'est pas encore activer, veuillez vérifier vos email et vos spams",
    "account_activated" : "Le compte est correctement activé",
    "adduser_success" : "Votre inscription sur le site GameGogs a réussi. Veuillez à présent vous connecter.",
    "data_missing" : "Vous devez renseigner tous les champs pour vous inscrire.",
    "dbconnect_error": "Il y a un problème pour se connecter à la base de données",
    "email_bad_format" : "Attention, l'adresse mail n'est pas au bon format",
    "email_empty" : "Vous devez saisir une adresse mail.",
    "exist_email" : "Le mail existe déjà",
    "exist_data" : "Le pseudo ou le mail existe déjà",
    "email_success" : "Merci, nous avons bien enregistré votre adresse mail",
    "email_failure" : "L'envoie du mail a échoué",
    "login_success" : "Vous êtes à présent connecté à votre compte.",
    "login_failure" : "Le mot de passe ou le pseudo n'existe pas dans la base de donnée.",
    "login_missing" : "Vous devez saisir un pseudo et un mot de passe pour vous connecter.",
    "logout_success" : "Vous êtes déconnecté/ A bientôt !",
    "max_connection_reached": "Le nombre maximum de connexions à la base de données a été atteint",
    "modifyuser_success" : "Les données on été modifiées avec succès",
    "modifyuser_fail" : "Les données n'ont pas pu être modifées",
    "password_bad_format" : "Attention, le mot de passe doit contenir ces caractères [0-9], [A-Z], [a-z] et !@#$%^&*()_+{}|:;<>,.?~[-]",
    "password_failure" : "Le mot de passe n'est pas bon",
    "password_verification_failed" : "La vérification du mot de passe a échoué",
    "request_error" : "La requête a échoué",
    "route_success" : "L'accès à cette route est autorisé et s'est déroulé correctement",
    "signin_success" : "Votre inscription sur le site GameGogs a réussi. Un mail vous a été envoyé par mail, veuillez vcliquer sur le lien d'activation pour activer votre compte.",
    "signin_failure" : "L'inscription ne s'est pas déroulée correctement",
    "signout_success" : "Vous êtes définitivement désinscrit du site. Vos données ont été détruites.",
    "signout_failure" : "Le pseudo ou le mail n'existe pas",
    "request_success" : "La requête a été effectuée avec succès",
    "invalid_action" : "Aucune action n'a été validée .... y'a une couille dans l'pâté !",
    "invalid_id" : "Aucun id n'est valide",
    "unknown_id" : "identifiant inconnu",
    "token_missing" : "Une erreur est survenue avec le token",
    "token_failure" : "Une erreur est survenue avec le token",
};

module.exports = { notificationMessages };